name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest black flake8 isort mypy sqlalchemy fastapi httpx
        
    - name: Run black
      run: black --check --diff .
    
    - name: Run flake8
      run: flake8 .
    
    - name: Run isort
      run: isort --check --diff .
    
    - name: Run mypy
      run: mypy .
    
    - name: Run tests
      run: pytest -v
