workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.7

stages: 
  - test

before_script:
  - pip install -r requirements.txt


unittest:
    stage: test
    script:
      - pytest tests

mypy:
    stage: test
    script:
      - mypy /src

black:
    stage: test
    script:
      - black --diff --check /src

isort:
    stage: test
    script:
      - isort --check-only --diff /src

flake8:
    stage: test
    script:
      - flake8 /src
